/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        legal: {
          bg: '#F8FAF8',
          header: '#FFFFFF',
          surface: '#FFFFFF',
          secondary: '#F3F7F5',
          elevated: '#E8F1EC',
          border: '#DCE6E0',
          text: '#16221C',
          textSec: '#66736C',
          textMuted: '#8C9A92',
          accent: '#176B4D',
          accentLight: '#176B4D',
          primary: '#12372A',
          hover: '#0F5139',
          tint: '#E8F1EC',
          danger: '#C94A4A',
          warning: '#D18A24',
          success: '#3E8E63',
          info: '#176B4D',
          action: '#176B4D',
        },
        lex: {
          bg: '#F8FAF8',
          card: '#FFFFFF',
          surface: '#FFFFFF',
          primary: '#12372A',
          action: '#176B4D',
          hover: '#0F5139',
          text: '#16221C',
          muted: '#66736C',
          faint: '#95A39B',
          border: '#DCE6E0',
          tint: '#E8F1EC',
          riskHigh: '#C94A4A',
          riskMed: '#D18A24',
          riskLow: '#3E8E63',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        serif: ['"DM Serif Display"', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
}
