import React from 'react'

function DocumentSummary({ summaryData, isLoading, error, onRetry }) {
  if (isLoading) {
    return (
      <div className="p-6 sm:p-8 rounded-2xl bg-white border border-[#DCE6E0] space-y-6 animate-pulse shadow-sm">
        <div className="flex items-center justify-between">
          <div className="h-6 w-44 bg-[#E8F1EC] rounded-md"></div>
          <div className="h-6 w-28 bg-[#E8F1EC] rounded-full"></div>
        </div>
        <div className="space-y-3">
          <div className="h-4 bg-[#F3F7F5] rounded w-full"></div>
          <div className="h-4 bg-[#F3F7F5] rounded w-11/12"></div>
          <div className="h-4 bg-[#F3F7F5] rounded w-4/5"></div>
        </div>
        <div className="space-y-3 pt-4 border-t border-[#DCE6E0]">
          <div className="h-5 w-36 bg-[#E8F1EC] rounded"></div>
          <div className="h-4 bg-[#F3F7F5] rounded w-full"></div>
          <div className="h-4 bg-[#F3F7F5] rounded w-5/6"></div>
          <div className="h-4 bg-[#F3F7F5] rounded w-3/4"></div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="p-6 sm:p-8 rounded-2xl bg-white border border-[#F5C2C2] space-y-4 text-center shadow-sm">
        <div className="w-12 h-12 rounded-full bg-[#FFF2F2] border border-[#F5C2C2] text-[#C94A4A] flex items-center justify-center mx-auto text-xl">
          ⚠️
        </div>
        <div className="space-y-1">
          <h3 className="text-base font-bold text-[#C94A4A]">
            Summarization Failed
          </h3>
          <p className="text-xs text-[#66736C] max-w-md mx-auto">{error}</p>
        </div>
        {onRetry && (
          <button
            onClick={onRetry}
            className="px-4 py-1.5 text-xs font-semibold rounded-xl bg-white hover:bg-[#F3F7F5] text-[#16221C] border border-[#DCE6E0] transition-colors shadow-2xs"
          >
            Retry Summarization
          </button>
        )}
      </div>
    )
  }

  if (!summaryData) {
    return (
      <div className="p-8 rounded-2xl bg-white border border-[#DCE6E0] text-center text-[#8C9A92] shadow-sm">
        No summary generated yet.
      </div>
    )
  }

  const { summary, key_points, document_type } = summaryData

  return (
    <div className="space-y-6">
      {/* Executive Summary Card */}
      <div className="p-6 sm:p-7 rounded-2xl bg-white border border-[#DCE6E0] shadow-sm space-y-6">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#DCE6E0] pb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-[#E8F1EC] border border-[#DCE6E0] flex items-center justify-center text-lg text-[#176B4D] shadow-2xs">
              📋
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-[#16221C] tracking-tight">
                Executive Document Summary
              </h2>
              <p className="text-xs text-[#66736C]">
                Synthesized high-level overview generated by AI
              </p>
            </div>
          </div>

          {document_type && (
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-[#E8F1EC] text-[#176B4D] border border-[#DCE6E0] tracking-wide">
              <span>📄</span> {document_type}
            </span>
          )}
        </div>

        {/* Plain English Summary */}
        <div className="space-y-2">
          <h3 className="text-[11px] font-bold text-[#176B4D] uppercase tracking-wider">
            Agreement Overview
          </h3>
          <div className="p-5 rounded-xl bg-[#F4F8F5] border border-[#DCE6E0] border-l-4 border-l-[#176B4D]">
            <p className="text-[#16221C] leading-relaxed text-sm sm:text-[15px] whitespace-pre-line font-sans font-normal">
              {summary}
            </p>
          </div>
        </div>

        {/* Key Takeaways */}
        {key_points && key_points.length > 0 && (
          <div className="space-y-3 pt-2">
            <div className="flex items-center justify-between">
              <h3 className="text-[11px] font-bold text-[#176B4D] uppercase tracking-wider flex items-center gap-1.5">
                <span>📌</span> Key Highlights &amp; Contractual Obligations
              </h3>
              <span className="text-[11px] text-[#8C9A92] font-mono font-medium">
                {key_points.length} {key_points.length === 1 ? 'point' : 'points'}
              </span>
            </div>

            <div className="grid grid-cols-1 gap-2.5">
              {key_points.map((point, index) => (
                <div
                  key={index}
                  className="flex items-start gap-3.5 p-4 rounded-xl bg-[#F8FAF8] border border-[#DCE6E0] hover:border-[#176B4D]/40 hover:bg-white transition-all duration-200"
                >
                  <span className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-[#E8F1EC] text-[#176B4D] border border-[#DCE6E0] text-xs font-bold font-mono shrink-0 mt-0.5">
                    {index + 1}
                  </span>
                  <span className="text-sm text-[#16221C] leading-relaxed flex-1 font-medium">
                    {point}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default DocumentSummary
